name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:  
      - name: Checkout repository
        with:
          fetch-depth: 2
        uses: actions/checkout@v2
      
      - name: Stop earlier containers 
        run: |
          chmod +x kill-older-container.sh
          ./kill-older-container.sh

      - name: Run tests
        run: mvn clean test

      - name: Docker build for the new container
        run: docker build -t java-springboot-be .

      - name: Docker run for the new container
        run: docker run -d -p 80:8080 java-springboot-be:latest
      
